- name: install apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - libglib2.0-dev
    - libpcap-dev
  become: yes
- name: install ndpi apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - libndpi-dev
    - libndpi-bin
  become: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "18"
- name: compile yaf ndpi
  script: scripts/compile_yaf_ndpi.sh
  become: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "18"
- name: compile yaf
  script: scripts/compile_yaf.sh
  become: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "16"
- name: copy systemd startup script of yaf ndpi
  template: src=templates/yaf_ndpi.service.j2 dest=/lib/systemd/system/yaf.service mode=0644
  become: yes
  notify: restart yaf
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "18"
    - yaf_systemd == true
- name: copy systemd startup script of yaf
  template: src=templates/yaf.service.j2 dest=/lib/systemd/system/yaf.service
  become: yes
  notify: restart yaf
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "16"
    - yaf_systemd == true
