- name: install apt-transport-https apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
  become: yes
- name: install filebeat apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - filebeat
  become: yes
- name: filebeat modules enable elasticsearch
  command: filebeat modules enable elasticsearch
  become: yes
  notify: restart filebeat
