- name: install apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - libglib2.0-dev
    - libssl-dev
    - openssl
  become: yes
- name: compile fixbuf ndpi
  script: scripts/compile_fixbuf_ndpi.sh
  become: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "16"
- name: compile fixbuf
  script: scripts/compile_fixbuf.sh
  become: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "18"
