- name: add GPG-KEY-elasticsearch
  script: scripts/add_GPG-KEY-elasticsearch.sh
  become: yes
- name: create elastic-6.x.list
  copy: src=files/elastic-6.x.list dest=/etc/apt/sources.list.d/elastic-6.x.list
  become: yes

