- name: add vm.max_map_count in /etc/sysctl.conf
  blockinfile:
    dest: /etc/sysctl.conf
    insertafter: EOF
    block: |
      vm.max_map_count=262144
  become: yes
- name: exec sysctl -p
  command: sysctl -p
  become: yes
- name: install elasticsearch apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - elasticsearch-oss={{ elasticsearch_oss_version }}
  become: yes
- name: install Open Distro for Elasticsearch
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - opendistroforelasticsearch
  become: yes
- name: edit thread_pool.search.queue_size in /etc/elasticsearch/elasticsearch.yml
  blockinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    insertafter: EOF
    block: |
      thread_pool.search.queue_size: {{ elasticsearch_thread_pool_search_queue_size }}
  become: yes
- name: edit the initial size of total heap space in /etc/elasticsearch/jvm.options
  replace:
    path: /etc/elasticsearch/jvm.options
    regexp: '^-Xms1g$'
    replace: '{{ elasticsearch_total_heap_space }}'
  become: yes
- name: edit the maximum size of total heap space in /etc/elasticsearch/jvm.options
  replace:
    path: /etc/elasticsearch/jvm.options
    regexp: '^-Xmx1g$'
    replace: '{{ elasticsearch_maximum_heap_space }}'
  become: yes
  notify: restart opendistro-elasticsearch
