- name: restart opendistro systemd
  systemd:
    name: opendistro.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes
  listen: restart opendistro
- name: wait elasticsearch uri module
  uri:
    uri: https://localhost:9200/
    url_username: admin
    url_password: admin
    force_basic_auth: yes
    use_proxy: no
    validate_certs: no
  register: this
  until: "'tagline' in this.content"
  retries: 10
  delay: 30
  listen: restart opendistro
- name: add yaf role
  script: scripts/role.yaf.sh
  register: result
  until: result.stdout.find('CREATED') != -1 or result.stdout.find('OK') != -1
  retries: 10
  delay: 30
  listen: restart opendistro
  when: snort_systemd == false
- name: add yaf and snort role
  script: scripts/role.yaf.snort.sh
  register: result
  until: result.stdout.find('CREATED') != -1 or result.stdout.find('OK') != -1
  retries: 10
  delay: 30
  listen: restart opendistro
  when: snort_systemd == true
- name: add yaf roles mapping
  script: scripts/rolesmapping.yaf.sh
  register: result
  until: result.stdout.find('CREATED') != -1 or result.stdout.find('OK') != -1
  retries: 10
  delay: 30
  listen: restart opendistro
- name: add yaf user
  script: scripts/user.yaf.sh {{ logstash_user }} {{ logstash_password }}
  register: result
  until: result.stdout.find('CREATED') != -1 or result.stdout.find('OK') != -1
  retries: 10
  delay: 30
  become: yes
  listen: restart opendistro
