{
 "title": "ElasticSearch YAF count",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "panels": [
  {
   "title": "flow count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "octetTotalCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "flows.octetTotalCount",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "flows.reverseOctetTotalCount",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "packetTotalCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "flows.packetTotalCount",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "flows.reversePacketTotalCount",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}