- name: restart opendistro-elasticsearch systemd
  systemd:
    name: elasticsearch.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes
  listen: restart opendistro-elasticsearch
- name: wait elasticsearch
  shell: curl -XGET https://localhost:9200/ -u admin:admin --insecure
  register: result
  until: result.stdout.find('tagline') != -1
  retries: 10
  delay: 30
  listen: restart opendistro-elasticsearch
- name: add yaf role
  script: scripts/role.yaf.sh
  register: result
  until: result.stdout.find('CREATED') != -1 or result.stdout.find('OK') != -1
  retries: 10
  delay: 30
  listen: restart opendistro-elasticsearch
  when: snort_systemd == false
- name: add yaf and snort role
  script: scripts/role.yaf.snort.sh
  register: result
  until: result.stdout.find('CREATED') != -1 or result.stdout.find('OK') != -1
  retries: 10
  delay: 30
  listen: restart opendistro-elasticsearch
  when: snort_systemd == true
- name: add yaf roles mapping
  script: scripts/rolesmapping.yaf.sh
  register: result
  until: result.stdout.find('CREATED') != -1 or result.stdout.find('OK') != -1
  retries: 10
  delay: 30
  listen: restart opendistro-elasticsearch
- name: add yaf user
  script: scripts/user_no_docker.yaf.sh {{ logstash_user }} {{ logstash_password }}
  register: result
  until: result.stdout.find('CREATED') != -1 or result.stdout.find('OK') != -1
  retries: 10
  delay: 30
  become: yes
  listen: restart opendistro-elasticsearch
