- name: install kibana apt packages
  apt: pkg={{ item }} update_cache=yes
  become: yes
  with_items:
    - kibana

- name: edit server.host in /etc/kibana/kibana.yml
  blockinfile:
    dest: /etc/kibana/kibana.yml
    insertafter: EOF
    block: |
      server.host: {{ kibana_server_host }}
      server.maxPayloadBytes: {{ kibana_server_maxPayloadBytes }}
      elasticsearch.requestTimeout: {{ kibana_elasticsearch_requestTimeout }}
  become: yes
  notify: restart kibana
