- name: install kibana apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - kibana
  become: yes
- name: edit server.host in /etc/kibana/kibana.yml
  blockinfile:
    dest: /etc/kibana/kibana.yml
    insertafter: EOF
    block: |
      server.host: {{ kibana_server_host }}
      server.maxPayloadBytes: {{ kibana_server_maxPayloadBytes }}
      elasticsearch.requestTimeout: {{ kibana_elasticsearch_requestTimeout }}
  become: yes
  notify: restart kibana
