- name: install kibana apt packages
  apt: pkg={{ item }} update_cache=yes
  become: yes
  with_items:
    - kibana

- name: edit server.host in /etc/kibana/kibana.yml
  blockinfile:
    dest: /etc/kibana/kibana.yml
    insertafter: EOF
    block: |
      server.host: "0.0.0.0"
      server.maxPayloadBytes: 2097152
  become: yes
  notify: restart kibana
