- name: create curator.list
  copy: src=files/curator.list dest=/etc/apt/sources.list.d/curator.list mode=0644
  become: yes
- name: install elasticsearch-curator
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - elasticsearch-curator
  become: yes
