#plathome: virtualbox, aws_ec2
plathome: virtualbox

#elasticsearch_vm: 1, 3, 5
elasticsearch_vm: 1

#elasticsearch_docker_nodes: 1, 3, 5
elasticsearch_docker_nodes: 1

timezone: Asia/Tokyo
kibana_server_host: "0.0.0.0"
kibana_server_maxPayloadBytes: 20971520
kibana_elasticsearch_requestTimeout: 300000
elasticsearch_thread_pool_search_queue_size: 100000
elasticsearch_total_heap_space: -Xms2g
elasticsearch_maximum_heap_space: -Xmx2g

#elasticstack_system: 6.x, 7.x, opendistro_docker, opendistro_apt
elasticstack_system: 6.x
super_mediator_systemd: true
yaf_systemd: true
logstash_systemd: true
filebeat_systemd: false
snort_systemd: false

#ntp_server: "local ntp server"
#ntp_server: 192.168.1.1

#capture_interface: enp0s8 (plathome: virtualbox), eth0 (plathome: aws_ec2)
capture_interface: enp0s8
snort_home_net: 10.0.0.0/24

#pulledpork_oinkcode: "your oinkcode"
#pulledpork_oinkcode: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

#when elasticstack_system: opendistro_docker, opendistro_apt
logstash_user: yaf
#logstash_password: yaf1234 # Automatic generation

use_geoip: false

elasticsearch_cluster_name: visualize_network_traffic
node01_ip_address: 192.168.33.11
node02_ip_address: 192.168.33.12
node03_ip_address: 192.168.33.13
node04_ip_address: 192.168.33.14
node05_ip_address: 192.168.33.15

disksize: 100GB

ELK_memory_docker_5nodes: 16384
ELK_memory_docker_3nodes: 12288
ELK_memory: 6144

EK_only_memory: 4096

#aws instance_type
aws_instance_type: t2.medium
