plathome: virtualbox

timezone: Asia/Tokyo
kibana_server_host: "0.0.0.0"
kibana_server_maxPayloadBytes: 20971520
kibana_elasticsearch_requestTimeout: 300000
elasticsearch_thread_pool_search_queue_size: 100000
elasticsearch_total_heap_space: -Xms2g
elasticsearch_maximum_heap_space: -Xmx2g

#elasticstack_system: 6.x, 7.x, opendistro_docker, opendistro_apt
elasticstack_system: 6.x
super_mediator_systemd: true
yaf_systemd: true
filebeat_systemd: false
snort_systemd: false

capture_interface: enp0s8
snort_home_net: 10.0.0.0/24

#when elasticstack_system: opendistro_docker, opendistro_apt
logstash_user: yaf
#logstash_password: yaf1234 # Automatic generation
