- name: install openjdk-8-jdk apt packages
  apt: pkg={{ item }} update_cache=yes
  become: yes
  with_items:
    - openjdk-8-jdk
- name: install apt-transport-https apt packages
  apt: pkg={{ item }} update_cache=yes
  become: yes
  with_items:
    - apt-transport-https
- name: install elasticsearch apt packages
  apt: pkg={{ item }} update_cache=yes
  become: yes
  with_items:
    - elasticsearch
- name: edit server.host in /etc/elasticsearch/elasticsearch.yml
  blockinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    insertafter: EOF
    block: |
      thread_pool.search.queue_size: {{ elasticsearch_thread_pool_search_queue_size }}
  become: yes
  notify: restart elasticsearch
