- name: install openjdk-8-jdk apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - openjdk-8-jdk
  become: yes
- name: install apt-transport-https apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
  become: yes
- name: install elasticsearch apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - elasticsearch
  become: yes
- name: edit cluster.name in /etc/elasticsearch/elasticsearch.yml
  blockinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    insertafter: '^#cluster.name: my-application$'
    block: |
      cluster.name: visualize_network_traffic
  become: yes
  when: elasticsearch_cluster is defined
- name: edit node.name in /etc/elasticsearch/elasticsearch.yml
  blockinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    insertafter: '^#node.name: node-1$'
    block: |
      node.name: {{ node }}
  become: yes
  when: elasticsearch_cluster is defined
- name: edit network.host in /etc/elasticsearch/elasticsearch.yml
  blockinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    insertafter: '^#network.host: 192.168.0.1$'
    block: |
      network.host: {{ node_ip_address }}
  become: yes
  when: elasticsearch_cluster is defined
- name: edit discovery.zen.ping.unicast.hosts in /etc/elasticsearch/elasticsearch.yml
  blockinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    insertafter: '^#discovery.zen.ping.unicast.hosts: ["host1", "host2"]$'
    block: |
      discovery.zen.ping.unicast.hosts: [ "{{ node01_ip_address }}" , "{{ node02_ip_address }}" , "{{ node03_ip_address }}" ]
  become: yes
  when: elasticsearch_cluster is defined
- name: edit discovery.zen.minimum_master_nodes in /etc/elasticsearch/elasticsearch.yml
  blockinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    insertafter: '^#discovery.zen.minimum_master_nodes:'
    block: |
      discovery.zen.minimum_master_nodes: 2
  become: yes
  when: elasticsearch_cluster is defined
- name: edit thread_pool.search.queue_size in /etc/elasticsearch/elasticsearch.yml
  blockinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    insertafter: EOF
    block: |
      thread_pool.search.queue_size: {{ elasticsearch_thread_pool_search_queue_size }}
  become: yes
- name: edit the initial size of total heap space in /etc/elasticsearch/jvm.options
  replace:
    path: /etc/elasticsearch/jvm.options
    regexp: '^-Xms1g$'
    replace: '{{ elasticsearch_total_heap_space }}'
  become: yes
- name: edit the maximum size of total heap space in /etc/elasticsearch/jvm.options
  replace:
    path: /etc/elasticsearch/jvm.options
    regexp: '^-Xmx1g$'
    replace: '{{ elasticsearch_maximum_heap_space }}'
  become: yes
  notify: restart elasticsearch
