- name: extract elastiflow
  unarchive:
    src: https://github.com/robcowart/elastiflow/archive/master.zip
    dest: ~/
    remote_src: yes
#- name: setup kibana for elastiflow
#  script: scripts/setup_kibana.sh
- name: copy logstash configuration file
  copy:
    src: /home/vagrant/elastiflow-master/logstash/elastiflow/
    dest: /etc/logstash/elastiflow/
    mode: preserve
    directory_mode: yes
  become: yes
- name: copy logstash service file
  copy:
    src: /home/vagrant/elastiflow-master/logstash.service.d/
    dest: /etc/systemd/system/logstash.service.d/
    mode: preserve
    directory_mode: yes
  become: yes
- name: edit pipeline.id in /etc/logstash/pipelines.yml
  blockinfile:
    dest: /etc/logstash/pipelines.yml
    insertafter: EOF
    block: |
      - pipeline.id: elastiflow
      path.config: "/etc/logstash/elastiflow/conf.d/*.conf"
  become: yes
- name: exec /usr/share/logstash/bin/system-install
  command: /usr/share/logstash/bin/system-install
  become: yes
  notify: restart logstash for elastiflow
