- name: extract elastiflow
  unarchive:
    src: https://github.com/robcowart/elastiflow/archive/master.zip
    dest: ~/
    remote_src: yes
- name: copy logstash configuration file
  copy:
    src: ~/elastiflow-master/logstash/elastiflow/
    dest: /etc/logstash/elastiflow/
    mode: preserve
    remote_src: yes
    directory_mode: yes
  become: yes
- name: copy logstash service file
  copy:
    src: ~/elastiflow-master/logstash/logstash.service.d/
    dest: /etc/systemd/system/logstash.service.d/
    mode: preserve
    remote_src: yes
    directory_mode: yes
  become: yes
- name: edit pipeline.id in /etc/logstash/pipelines.yml
  blockinfile:
    dest: /etc/logstash/pipelines.yml
    insertafter: EOF
    block: |
      - pipeline.id: elastiflow
      path.config: "/etc/logstash/elastiflow/conf.d/*.conf"
  become: yes
