- name: pull opendistro elasticsearch docker image
  command: docker pull amazon/opendistro-for-elasticsearch:{{ opendistro_version }}
  become: yes
- name: pull opendistro kibana docker image
  command: docker pull amazon/opendistro-for-elasticsearch-kibana:{{ opendistro_version }}
  become: yes
- name: add vm.max_map_count in /etc/sysctl.conf
  blockinfile:
    dest: /etc/sysctl.conf
    insertafter: EOF
    block: |
      vm.max_map_count=262144
  become: yes
- name: exec sysctl -p
  command: sysctl -p
  become: yes
- name: mkdir /usr/local/etc/opendistro
  file: path=/usr/local/etc/opendistro state=directory owner=root group=root mode=0755
  become: yes
- name: copy from docker-compose_elasticsearch_1node.yml.j2
  template: src=templates/docker-compose_elasticsearch_1node.yml.j2 dest=/usr/local/etc/opendistro/docker-compose.yml
  become: yes
  when: elasticsearch_docker_nodes == 1
- name: copy from docker-compose_elasticsearch_3nodes.yml.j2
  template: src=templates/docker-compose_elasticsearch_3nodes.yml.j2 dest=/usr/local/etc/opendistro/docker-compose.yml
  become: yes
  when: elasticsearch_docker_nodes == 3
- name: copy from docker-compose_elasticsearch_5nodes.yml.j2
  template: src=templates/docker-compose_elasticsearch_3nodes.yml.j2 dest=/usr/local/etc/opendistro/docker-compose.yml
  become: yes
  when: elasticsearch_docker_nodes == 5
- name: copy systemd startup script
  copy: src=files/opendistro.service dest=/lib/systemd/system/opendistro.service
  become: yes
  notify: restart opendistro

