- name: install kibana apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - opendistroforelasticsearch-kibana
  become: yes
- name: edit cluster.name in /etc/elasticsearch/elasticsearch.yml
  replace:
    path: /etc/kibana/kibana.yml
    regexp: '^elasticsearch.url: https://localhost:9200'
    replace: '#elasticsearch.url: https://localhost:9200'
  become: yes
  when: elasticstack_version == "7.x"
- name: edit server.host in /etc/kibana/kibana.yml
  blockinfile:
    dest: /etc/kibana/kibana.yml
    insertafter: EOF
    block: |
      server.host: {{ kibana_server_host }}
      server.maxPayloadBytes: {{ kibana_server_maxPayloadBytes }}
      elasticsearch.requestTimeout: {{ kibana_elasticsearch_requestTimeout }}
      elasticsearch.hosts: ["https://127.0.0.1:9200"]
  become: yes
  notify: restart opendistro-kibana
  when: elasticsearch_vm == 1
- name: edit elasticsearch.hosts in /etc/kibana/kibana.yml
  blockinfile:
    dest: /etc/kibana/kibana.yml
    insertafter: EOF
    block: |
      server.host: {{ kibana_server_host }}
      server.maxPayloadBytes: {{ kibana_server_maxPayloadBytes }}
      elasticsearch.requestTimeout: {{ kibana_elasticsearch_requestTimeout }}
      elasticsearch.hosts: ["https://{{ node01_ip_address }}:9200", "https://{{ node02_ip_address }}:9200", "https://{{ node03_ip_address }}:9200"]
  become: yes
  notify: restart opendistro-kibana
  when: elasticsearch_vm == 3
