- name: Install ELK6
  hosts: testserver
  vars_files:
    - version_elastiflow.yml
    - config.yml
    - config_elastiflow.yml
  environment:
    yaf_version: "{{ yaf_version }}"
    fixbuf_version: "{{ fixbuf_version }}"
  connection: local
  pre_tasks:
    - set_fact: home_dir="{{ ansible_env.HOME }}"
    - name: set timezone
      script: scripts/set_timezone.sh {{ timezone }}
      become: yes
    - name: install apt packages
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
        - build-essential
        - ntp
        - git
        - curl
        - jq
        - wireshark
      become: yes
    - name: mkdir
      file: path={{ item }}  state=directory mode=0755
      with_items:
        - ~/yaf/log
        - ~/bin
        - ~/etc
    - name: copy shell scripts
      copy: src=files/{{ item }} dest=~/bin/{{ item }} mode=0755
      with_items:
        - yaf.sh
    - name: capture interface up
      blockinfile:
        dest: /etc/network/interfaces.d/50-cloud-init.cfg
        insertafter: EOF
        block: |
          auto {{ capture_interface }}
          iface {{ capture_interface }} inet manual
      become: yes
      when:
        - ansible_distribution == "Ubuntu"
        - ansible_distribution_major_version == "16"
  roles:
    - role: docker
    - role: docker-compose
    - role: manual-iface
    - role: libp0f
    - role: fixbuf
    - role: yaf
    - role: elastiflow_docker
    - role: grafana
