- name: Install ELK6
  hosts: testserver
  become: True
  tasks: 
    - name: add GPG-KEY-elasticsearch
      script: scripts/add_GPG-KEY-elasticsearch.sh
    - name: create elastic-6.x.list
      copy: src=files/elastic-6.x.list dest=/etc/apt/sources.list.d/elastic-6.x.list
    - name: create curator.list
      copy: src=files/curator.list dest=/etc/apt/sources.list.d/curator.list
    - name: install apt packages
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      become: True
      with_items:
        - ntp
        - git
        - curl
        - jq
        - wireshark
        - libglib2.0-dev
        - libfixbuf3
        - libfixbuf3-dev
        - libpcap-dev
        - libndpi-dev
        - libndpi-bin
        - mysql-server
        - mysql-client
        - libmysqlclient-dev
        - apt-transport-https
        - openjdk-8-jdk
        - elasticsearch
        - logstash
        - kibana
        - elasticsearch-curator
    - name: compile libp0f.tgz
      script: scripts/compile_libp0f.sh
      become: yes
    - name: compile yaf
      script: scripts/compile_yaf.sh
      become: yes
    - name: compile super_mediator
      script: scripts/compile_super_mediator.sh
      become: yes
    - name: mkdir /home/ubuntu/yaf/json
      file: path=/home/ubuntu/yaf/json state=directory owner=ubuntu group=ubuntu mode=0755
    - name: mkdir /home/ubuntu/yaf/log
      file: path=/home/ubuntu/yaf/log state=directory owner=ubuntu group=ubuntu mode=0755
    - name: mkdir /home/ubuntu/bin
      file: path=/home/ubuntu/bin state=directory owner=ubuntu group=ubuntu mode=0755
    - name: copy yaf.sh
      copy: src=files/yaf.sh dest=/home/ubuntu/bin/yaf.sh mode=0755
    - name: copy yaf_ndpi.sh
      copy: src=files/yaf_ndpi.sh dest=/home/ubuntu/bin/yaf_ndpi.sh mode=0755
    - name: copy super_mediator.sh
      copy: src=files/super_mediator.sh dest=/home/ubuntu/bin/super_mediator.sh mode=0755
    - name: copy super_mediator config file
      copy: src=files/super_mediator.conf dest=/usr/local/etc/super_mediator.conf
    - name: copy logstash config file
      copy: src=files/logstash_ipfix.conf dest=/etc/logstash/conf.d/logstash_ipfix.conf
    - name: edit kibana config file
      blockinfile:
        dest: /etc/kibana/kibana.yml
        insertafter: '^#server.host: "localhost"'
        content: 'server.host: "0.0.0.0"'
    - name: restart elasticsearch.service
      systemd:
        name: elasticsearch.service
        state: restarted
        daemon_reload: yes
        enabled: yes
      become: yes
    - name: restart logstash.service
      systemd:
        name: logstash.service
        state: restarted
        daemon_reload: yes
        enabled: yes
      become: yes
    - name: restart kibana.service
      systemd:
        name: kibana.service
        state: restarted
        daemon_reload: yes
        enabled: yes
      become: yes
