- name: Install ELK6
  hosts: testserver
  vars_files:
    - version.yml
    - config_aws_ec2.yml
  environment:
    super_mediator_version: "{{ super_mediator_version }}"
    yaf_version: "{{ yaf_version }}"
    fixbuf_version: "{{ fixbuf_version }}"
  connection: local
  pre_tasks:
    - set_fact: home_dir="{{ ansible_env.HOME }}"
    - name: set timezone
      script: scripts/set_timezone.sh {{ timezone }}
      become: yes
    - name: install apt packages
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
        - build-essential
        - ntp
        - git
        - curl
        - jq
        - wireshark
      become: yes
    - name: mkdir
      file: path={{ item }}  state=directory mode=0755
      with_items:
        - ~/yaf/json
        - ~/yaf/log
        - ~/bin
        - ~/etc
        - ~/.curator
    - name: copy shell scripts
      copy: src=files/{{ item }} dest=~/bin/{{ item }} mode=0755
      with_items:
        - yaf.sh
        - super_mediator.sh
        - logstash_config_test.sh
    - name: copy yaf_ndpi shell scripts
      copy: src=files/{{ item }} dest=~/bin/{{ item }} mode=0755
      with_items:
        - yaf_ndpi.sh
      when:
        - ansible_distribution == "Ubuntu"
        - ansible_distribution_major_version == "16"
    - name: copy curator file
      copy: src=files/{{ item }} dest=~/.curator/{{ item }}
      with_items:
        - curator.yml
        - delete_indices_yaf.yml
    - name: install curator cron job
      cron: name="curator" minute="5" hour="2" user={{ ansible_env.USER }} job="curator ~/.curator/delete_indices_yaf.yml"
    - name: capture interface up
      blockinfile:
        dest: /etc/network/interfaces.d/50-cloud-init.cfg
        insertafter: EOF
        block: |
          auto {{ capture_interface }}
          iface {{ capture_interface }} inet manual
      become: yes
      when:
        - ansible_distribution == "Ubuntu"
        - ansible_distribution_major_version == "16"
  roles:
    - role: manual-iface
    - role: libp0f
    - role: fixbuf
    - role: yaf
    - role: super_mediator
    - role: elasticsearch
    - role: logstash
    - role: kibana
    - role: elasticsearch-curator
    - role: grafana
