# -*- mode: ruby -*-
# vi: set ft=ruby :

config_type = "elasticsearch_1node"
load "./Vagrantfile.local" if File.exist?("./Vagrantfile.local")

load "./Vagrantfile.elasticsearch_1node" if config_type == "elasticsearch_1node"
load "./Vagrantfile.elasticsearch_3nodes" if config_type == "elasticsearch_3nodes"
