# -*- mode: ruby -*-
# vi: set ft=ruby :

$visualize_network_traffic_config_type = "elasticsearch_1node"
load "./Vagrantfile.local" if File.exist?("./Vagrantfile.local")

load "./Vagrantfile.elasticsearch_1node" if $visualize_network_traffic_config_type == "elasticsearch_1node"
load "./Vagrantfile.elasticsearch_3nodes" if $visualize_network_traffic_config_type == "elasticsearch_3nodes"
load "./Vagrantfile.aws_ec2_1node" if $visualize_network_traffic_config_type == "aws_ec2_1node"
load "./Vagrantfile.elasticsearch_snort_1node" if $visualize_network_traffic_config_type == "elasticsearch_snort_1node"
