- name: create influxdb.list 
  script: scripts/create_influxdb.list.sh
  become: yes
- name: install influxdb apt packages
  apt: pkg={{ item }} update_cache=yes
  become: yes
  with_items:
    - influxdb
- name: edit influxdb config file
  blockinfile:
    dest: /etc/influxdb/influxdb.conf
    insertafter: '# max-values-per-tag = 100000'
    content: 'max-values-per-tag = 0'
  become: yes
  notify: restart influxdb
