- name: copy systemd startup script of manual-iface
  template: src=templates/manual-iface.service.j2 dest=/lib/systemd/system/manual-iface.service mode=0644
  become: yes
  notify: restart manual-iface
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "18"
