- name: install apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - libglib2.0-dev
    - mysql-server
    - mysql-client
    - libmysqlclient-dev
  become: yes
- name: compile yaf
  script: scripts/compile_yaf.sh
  become: yes
- name: compile super_mediator
  script: scripts/compile_super_mediator.sh
  become: yes
