- name: install apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - libglib2.0-dev
    - mysql-server
    - mysql-client
    - libmysqlclient-dev
  become: yes
- name: compile super_mediator
  script: scripts/compile_super_mediator.sh
  become: yes
- name: copy super_mediator config file
  template: src=templates/super_mediator.conf.j2 dest=/usr/local/etc/super_mediator.conf
  become: yes
- name: edit /etc/crontab
  blockinfile:
    dest: /etc/crontab
    insertafter: EOF
    block: |
      1 5 * * * find /home/vagrant/yaf/json -mtime +29 -exec rm -f {} \;
  become: yes
- name: copy systemd startup script
  copy: src=files/super_mediator.service dest=/lib/systemd/system/super_mediator.service
  become: yes
  notify: restart super_mediator
