- name: install packages to allow apt to use a repository over HTTPS
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
  become: yes
- name: Add Docker's official GPG key
  script: scripts/add_GPG-KEY-docker.sh
  become: yes
- name: set up the stable repository
  script: scripts/add_apt-repository.sh
  become: yes
- name: install the latest version of Docker CE and containerd
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  become: yes
