- name: install logstash apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - logstash
  become: yes
  when: elasticstack_system == '6.x' or elasticstack_system == '7.x'
- name: install logstash-oss apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - logstash-oss
  become: yes
  when: elasticstack_system == 'opendistro_docker' or elasticstack_system == 'opendistro_apt'
- name: copy logstash snort config file
  template: src=templates/logstash_snort.conf.j2 dest=/etc/logstash/conf.d/logstash_snort.conf
  become: yes
  when: snort_systemd == true
- name: copy logstash config file
  template: src=templates/logstash_ipfix.conf.j2 dest=/etc/logstash/conf.d/logstash_ipfix.conf
  become: yes
  notify: restart logstash
