- name: install openjdk-8-jdk apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - openjdk-8-jdk
  become: yes
- name: install logstash apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - logstash
  become: yes
- name: edit the initial size of total heap space in /etc/logstash/jvm.options
  replace:
    path: /etc/logstash/jvm.options
    regexp: '^-Xms1g$'
    replace: '{{ logstash_total_heap_space }}'
  become: yes
- name: edit the maximum size of total heap space in /etc/logstash/jvm.options
  replace:
    path: /etc/logstash/jvm.options
    regexp: '^-Xmx1g$'
    replace: '{{ logstash_maximum_heap_space }}'
  become: yes
  notify: restart logstash
